.ti 0
\l'\n(.lu'
.SH nav_exclude: true
.TH scedit 1 "January 2022" IBMi "Edit configs for Service Commander"
.SH NAME
.PP
\fBscedit\fP \- a tool for editing service definitions for Service Commander.
.SH SYNOPSIS
.PP
\fB\fCusage: scedit <service_name>\fR
.SH DESCRIPTION
.PP
The \fB\fCscedit\fR command will locate the configuration file where the definition
for the service is stored. It will then launch a terminal\-based editor
.PP
If you prefer a certain terminal\-based editor, you can customize the editor by
use of the \fB\fCEDITOR\fR environment variable.
.SH OPTIONS
.PP
Usage of the command is summarized as:
.PP
.RS
.nf
usage: scedit <service_name>
.fi
.RE
