.ti 0
\l'\n(.lu'
.SH nav_exclude: true
.TH scopenports 1 "January 2022" IBMi "Open Ports Utility"
.SH NAME
.PP
\fBscopenports\fP \- a tool for showing which TCP/IP ports are open on an IBM i server.
.SH SYNOPSIS
.PP
\fB\fCscopenports  [options]\fR
.SH DESCRIPTION
.PP
The \fBscopenports\fP tool is used for showing which TCP/IP ports are open on an IBM i server.
This tool is part of the \fBService Commander\fP for IBM i package.
.PP
\fBscopenports\fP will display the ports that are open on the server, in a table, as in the following example:
.TS
allbox;
cb cb cb
l l l
.
IP Address	Port Number	Port Description
10.0.0.2	22	sshd (System Secure Shell server)
.TE
.PP
If you find the list is too extensive, try using the \fB\fC\-\-mine\fR option.  This will limit the output to only show the ports that relate to your jobs (The job user profile name, used to run the scopenports utility).
.PP
If you wish the list to show a friendly name for the port, use service commander (sc) to define the names you wish to use.
.PP
Run the \fB\fCsc_install_defaults\fR command to initialise common defaults.
.SH OPTIONS
.PP
Usage of the command is summarized as:
```
Usage: scopenports  [options]
.PP
.RS
.nf
Valid options include:
    \-v: verbose mode
    \-\-mine: only show ports that are running under your user profile
.fi
.RE
.PP
.RS
.nf
.fi
.RE
