#!/QOpenSys/pkgs/bin/bash

SCTARGET=${SCTARGET:-SCOMMANDER}

/QOpenSys/usr/bin/system -Kkpiebv "RMVTCPSVR SVRSPCVAL(*SC)" || echo "TCPSVR has not been installed"
/QOpenSys/usr/bin/system -Kkpiebv "DLTMOD MODULE(${SCTARGET}/SC)" || echo "module doesn't exist"
/QOpenSys/usr/bin/system -Kkpiebv "DLTPGM PGM(${SCTARGET}/SC)" || echo "program doesn't exist"
/QOpenSys/usr/bin/system -Kkpiebv "DLTLIB LIB(${SCTARGET})" || echo "lib doesn't exist"

echo 'SUCCESS!!'
