#!/QOpenSys/pkgs/bin/bash
TARGET_DIR="$HOME/.sc/services"
mkdir -p $TARGET_DIR
function install_if_executable {
    if [[ -x "$1" ]]; then
        echo "installing $2..."
        cp "$2" $TARGET_DIR
    else
        echo "not installing $2..."
    fi
}
function install {
        echo "installing $1..."
        cp "$1" $TARGET_DIR
}
function install_apache {
    echo "installing apache server $1..."

    if [ ! -d "$1/htdocs" ]; then
        echo "OOPS\!\! Not an Apache server here..."
        return
    fi
    PORT=$(grep -iE '^Listen ' ./$1/conf/httpd.conf |  sed 's|.*:||g' | tail -n 1)
    if [[ "" == "$PORT" ]]; then
        echo "OOPS\!\! Not an Apache server here..."
        return
    fi
        YAMLFILE="$TARGET_DIR/apache_$(echo "$1" | awk '{ print tolower($0) }').yaml"
        echo "name: Apache server $1" > $YAMLFILE
        echo "start_cmd: system \"STRTCPSVR SERVER(*HTTP) HTTPSVR($1)\"" >> $YAMLFILE
        echo "stop_cmd: system \"ENDTCPSVR SERVER(*HTTP) HTTPSVR($1)\"" >> $YAMLFILE
        echo 'check_alive: port' >> $YAMLFILE
        echo "check_alive_criteria: $PORT" >> $YAMLFILE
        echo "groups:" >> $YAMLFILE
        echo ' - "apache"' >> $YAMLFILE
}
cd /QOpenSys/pkgs/lib/sc/samples
for HOSTSVR in $(find host_servers -name as-\*)
do
    install $HOSTSVR
done
for TCPSVR in $(find system_tcpsvr -name \*.yaml)
do
    install $TCPSVR
done
install navigator.yaml
install_if_executable /QOpenSys/pkgs/bin/mysqld mariadb.yaml
install_if_executable /QOpenSys/pkgs/bin/crond crond.yaml

cd /www

for APACHE in $(ls)
do
    install_apache $APACHE
done
