#!/QOpenSys/pkgs/bin/bash
TARGET_DIR="$HOME/.sc/services"
mkdir -p $TARGET_DIR
function install_if_executable {
    if [[ -x "$1" ]]; then
        echo "installing $2..."
        cp "$2" $TARGET_DIR
    else
        echo "not installing $2..."
    fi
}
function install {
    echo "installing $1..."
    cp "$1" $TARGET_DIR
}
function print_usage {
    echo "usage: sc_install_defaults [options]"
    echo ""
    echo "    valid options include:"
    echo "        -h            : display help"
    echo "        --apache      : autocreate from apache instances (default)"
    echo "        --system      : install common system TCP servers (default)"
    echo "        --cleanupv0   : clean up files created by v0 (default)"
    echo "        --noapache    : don't autocreate from apache instances"
    echo "        --nosystem    : don't install common system TCP servers"
    echo "        --nocleanupv0 : don't clean up files created by v0"
    echo "        --global      : install for all users"
    echo "        --user        : install for current user (default)"
    echo ""
    exit 0
}
function cleanup_v0 {
    echo "Cleaning up v0 files..."
    for VZERO in as-central.yaml as-database.yaml as-dtaq.yaml as-file.yaml as-netprt.yaml as-rmtcmd.yaml as-signon.yaml as-svrmap.yaml as-central-s.yaml as-database-s.yaml as-dtaq-s.yaml as-file-s.yaml as-netprt-s.yaml as-rmtcmd-s.yaml as-signon-s.yaml ddm.yaml directoryserver.yaml ftp.yaml netserver.yaml sshd.yaml telnet.yaml system_tcpsvr_secure ddm-ssl.yaml directoryserver-ssl.yaml telnet-ssl.yaml
    do
        rm -f $HOME/.sc/services/$VZERO
    done
}
function install_apache {
    echo "installing apache server $1..."

    if [ ! -d "$1/htdocs" ]; then
        echo "OOPS\!\! Not an Apache server here..."
        return
    fi
    PORT=$(grep -iE '^Listen ' ./$1/conf/httpd.conf |  sed 's|.*:||g' | tail -n 1)
    if [[ "" == "$PORT" ]]; then
        echo "OOPS\!\! Not an Apache server here..."
        return
    fi
        YAMLFILE="$TARGET_DIR/apache_$(echo "$1" | awk '{ print tolower($0) }').yaml"
        echo "name: Apache server $1" > $YAMLFILE
        echo "start_cmd: system \"STRTCPSVR SERVER(*HTTP) HTTPSVR($1)\"" >> $YAMLFILE
        echo "stop_cmd: system \"ENDTCPSVR SERVER(*HTTP) HTTPSVR($1)\"" >> $YAMLFILE
        echo 'check_alive: port' >> $YAMLFILE
        echo "check_alive_criteria: $PORT" >> $YAMLFILE
        echo "groups:" >> $YAMLFILE
        echo ' - "apache"' >> $YAMLFILE
}

DO_CLEANUP="1"
DO_SYSCOMMON="1"
DO_APACHE="0"
for i in "$@"; do
    case $i in
    -h|--help)
        print_usage
        ;;
    --apache)
        DO_APACHE="1"
        ;;
    --system)
        DO_SYSCOMMON="1"
        ;;
    --cleanupv0)
        DO_CLEANUP="1"
        ;;
    --noapache)
        DO_APACHE="0"
        ;;
    --nosystem)
        DO_SYSCOMMON="0"
        ;;
    --nocleanupv0)
        DO_CLEANUP="0"
        ;;
    --global)
        TARGET_DIR="/QOpenSys/etc/sc/services"
        ;;
    --user)
        TARGET_DIR="$HOME/.sc/services"
        ;;
    *)
        # unknown option
        exec 1>&2
        echo "Unknown option: $i"
        print_usage
        ;;
    esac
done
if [ "1" == "$DO_CLEANUP" ]; then
    cleanup_v0
fi

cd /QOpenSys/pkgs/lib/sc/samples
if [ "1" == "$DO_SYSCOMMON" ]; then
    for HOSTSVR in $(find host_servers -name \*.yaml)
    do
        install $HOSTSVR
    done
    for TCPSVR in $(find system_tcpsvr -name \*.yaml)
    do
        install $TCPSVR
    done
    for SYSCOMMON in $(find system_common -name \*.yaml)
    do
        install $SYSCOMMON
    done
fi
install_if_executable /QOpenSys/pkgs/bin/mysqld mariadb.yaml
install_if_executable /usr/local/mariadb/bin/mysqld zenddbi.yaml
install_if_executable /QOpenSys/pkgs/bin/crond crond.yaml

cd /www

if [ "1" == "$DO_APACHE" ]; then
    for APACHE in $(ls)
    do
        install_apache $APACHE
    done
fi
